### ISSUE TITLE
Overheating and fps unlocker not working

### ISSUE THREAD

**Issue by I-T-LE** [OrigamingWasTaken/appleblox#10]
never happened before for me

**Comment by OrigamingWasTaken** [comment]
What is your Mac model, version and what version of AppleBlox are you using?

**Comment by atomiciscool** [comment]
on mini mac fps unlocker doesn't work too

**Comment by OrigamingWasTaken** [comment]
I can't help if you don't provide more information.

**Comment by OrigamingWasTaken** [comment]
Closing as no information has been provided to help fix the issue
