### ISSUE TITLE
Same account launched from different account device.

### ISSUE THREAD

**Issue by ImBannables** [OrigamingWasTaken/appleblox#11]
Same account launched from different account device. (264) I am using 2 different accounts and this error is popping up

**Comment by ImBannables** [comment]
Latest release on the appleblox website and MacBookPro15,1

**Comment by ImBannables** [comment]
I downloaded the nightly version and it fixed my issue but now after about an hour tabs start closing out of nowhere.. I started with 6, ended with 3

**Comment by AngrySausage** [comment]
Send your logs, otherwise we can't help you

**Comment by OrigamingWasTaken** [comment]
This is a Roblox issue.

**Comment by OrigamingWasTaken** [comment]
Sorry didn't see that you had another issue, please send your logs so we can help you (appleblox.log)

**Comment by YousufSSyed** [comment]
I have the same issue and tried reproducing it but couldn't. Here's my `appleblox.log` file

[appleblox.log](https://github.com/user-attachments/files/16715349/appleblox.log)

**Comment by OrigamingWasTaken** [comment]
Your file is empty, also right now the multi instance option is buggy and unstable. All bugs relating to it will be fixed in 0.8.0!

**Comment by YousufSSyed** [comment]
Ok thanks.

> Your file is empty

I had a feeling it wouldn't be very useful lol

**Comment by OrigamingWasTaken** [comment]
Not enough informations to reproduce
