### ISSUE TITLE
Fast Flags not working

### ISSUE THREAD

**Issue by timuriasik** [OrigamingWasTaken/appleblox#12]
When i open "fast flags" tab it shows a grey tab and doesnt let me click off until i reopen the app

**Comment by PurvisiLOL** [comment]
Please run this command in your terminal to fix the issue.

`rm -rf ~/Library/Application\ Support/AppleBlox/config/fastflags.json`

Fixed in update 0.8.0 NOT released yet.

**Comment by OrigamingWasTaken** [comment]
Known bug. Fixed in 0.8.0
