### ISSUE TITLE
Allow window resizing and/or Fullscreen

### ISSUE THREAD

**Issue by bdc0der** [OrigamingWasTaken/appleblox#13]
I've noticed (at least as far as the nightly builds go,) the app doesn't support window resizing or fullscreening. This would be a handy thing to have, mainly because in the fast flag editor there are one or two flags I have copied and pasted that are very long, and they crowd out any room for me to type anything in (like boolean values, integers, etc. )

Regardless of how this is taken, I would like to profusely thank the dev(s?) for making this app, it has made my Roblox experience a lot better.

**Comment by PurvisiLOL** [comment]
I can ask Ori to add a copy button.

**Comment by OrigamingWasTaken** [comment]
> I've noticed (at least as far as the nightly builds go,) the app doesn't support window resizing or fullscreening. This would be a handy thing to have, mainly because in the fast flag editor there are one or two flags I have copied and pasted that are very long, and they crowd out any room for me to type anything in (like boolean values, integers, etc. )
> 
> Regardless of how this is taken, I would like to profusely thank the dev(s?) for making this app, it has made my Roblox experience a lot better.

The app cannot be resized because I suck at CSS and the UI isn't responsive.
But I will make the flags editor better, it's pretty bad right now.

**Comment by bdc0der** [comment]
Alright cool
