### ISSUE TITLE
FastFlag editor save/load presets (feature request)

### ISSUE THREAD

**Issue by bdc0der** [OrigamingWasTaken/appleblox#15]
Maybe it's just me, but it's kinda a pain in the rear to repeatedly disable certain fast flags when I switch games, (especially since I usually can't make heads or tails of what the fast flag does just by it name)
(e.g. turning on fps boosting fast flags in a laggy game but then turning them off in a game where graphics quality is everything [repeating the process])

Solution: Add some kind of feature to allow users to save files/folders that contain multiple fast flags to make it easier.

**Comment by OrigamingWasTaken** [comment]
Good idea. I will add that as "Flags profiles". For now if you want to enable a flag only for a game, you can do it like this:

You need to add `_PlaceFilter` after the flag name and `;<place id here>`

Exemple: `MyAwesomeFlag_PlaceFilter: true;123456`

**Comment by bdc0der** [comment]
Alright, sounds good.
