### ISSUE TITLE
- Roblox Infinitely updating and showing a Connection error. -

### ISSUE THREAD

**Issue by gitultra75848** [OrigamingWasTaken/appleblox#4]
Hello, so basically in a short summary this is what happend.

1; Download The arm64 zip file from the releases page and unzip it.

2; Place the .app file in the Applications folder and open it.

3; Click Launch and find out it shows a connection error and a "Configuring Roblox" popup, after that finishes and it says "Roblox is Installed", I click Ok and it stays on the Connection Error page no matter how many Times I click retry, and when i quit the Roblox Player and click Launch again, it does the same thing.

I have tried Uninstalling and re-installing and it didn't work. any ideas?

Running on a Macbook Pro M1, 2021 Model.

(note: sorry for the closing and reopening, missclick.)

**Comment by OrigamingWasTaken** [comment]
Could you link some screenshots?
Also does this happen when launching Roblox normally?

**Comment by OrigamingWasTaken** [comment]
Mmmmh that's really weird. Where is the app you open to use Roblox (Roblox.app) located?

Also please open the **Misc** tab in AppleBlox, and press "Open log file". Then send the file here.

**Comment by gitultra75848** [comment]
> Mmmmh that's really weird. Where is the app you open to use Roblox (Roblox.app) located?
> 
> Also please open the **Misc** tab in AppleBlox, and press "Open log file". Then send the file here.

Which Roblox.app file? the normal one or AppleBlox one?
Also, Sure.


[appleblox.log](https://github.com/user-attachments/files/16114239/appleblox.log)

**Comment by OrigamingWasTaken** [comment]
The normal roblox app.
If you press the "Write ClientAppSettings.json" button in the **Misc** tab, and then launch Roblox normally without AppleBlox, does this issue still occur?

**Comment by OrigamingWasTaken** [comment]
Ah yes that explains. I didn't think Roblox could be installed in user applications.
The app opens the Roblox at `/Applications/Roblox.app`, not `/Users/<user>/Applications/Roblox.app`

Can you try moving `/Users/<user>/Applications/Roblox.app` to `/Applications`?

(To revert the button you can just launch from the app event if it doesn't work, it will remove the file)

**Comment by gitultra75848** [comment]
> Ah yes that explains. I didn't think Roblox could be installed in user applications. The app opens the Roblox at `/Applications/Roblox.app`, not `/Users/<user>/Applications/Roblox.app`
> 
> Can you try moving `/Users/<user>/Applications/Roblox.app` to `/Applications`?
> 
> (To revert the button you can just launch from the app event if it doesn't work, it will remove the file)

Ohh, that explains it. I'll try that now, thanks.

**Comment by OrigamingWasTaken** [comment]
You can move the app for now if you want but I'll fix this in the next release ^^

If you don't have any more problem I'll close this issue now.

**Comment by gitultra75848** [comment]
> You can move the app for now if you want but I'll fix this in the next release ^^
> 
> If you don't have any more problem I'll close this issue now.

Asked my Dad for the admin password and he said no, sucks that I can't move it to /Applications, but it'd be appreciated if you fixed this on the next release, thanks.

**Comment by OrigamingWasTaken** [comment]
Oh okay.

Then I will notify you when the update is released!

**Comment by gitultra75848** [comment]
> Oh okay.
> 
> Then I will notify you when the update is released!

Thanks!

**Comment by OrigamingWasTaken** [comment]
@gitultra75848 This issue should now be fixed in the latest release. If you still have this bug, please tell me ^^

**Comment by gitultra75848** [comment]
> @gitultra75848 This issue should now be fixed in the latest release. If you still have this bug, please tell me ^^

Alright, I'll test it in a bit. thanks.

**Comment by OrigamingWasTaken** [comment]
Have the new releases worked for you?

**Comment by OrigamingWasTaken** [comment]
I'll close this as this should now be fixed
