### ISSUE TITLE
Shadows don't render when using MoltenVK (vulken)

### ISSUE THREAD

**Issue by Wvtched** [OrigamingWasTaken/appleblox#5]
Metal Roblox (apple's graphics API but has crappy perfomence)

![Screenshot 2024-07-06 at 6 48 48 PM](https://github.com/OrigamingWasTaken/appleblox/assets/162759764/cd1dd65a-a5b7-4218-8b46-3590f9875ff6)

MoltenVK Roblox (has very good performance but shadows don't render)

![Screenshot 2024-07-06 at 6 51 01 PM](https://github.com/OrigamingWasTaken/appleblox/assets/162759764/6007ca26-1555-4faa-8b25-23439bcf9846)

this is probably just for me so its okay if you don't fix it

**Comment by OrigamingWasTaken** [comment]
This is a Roblox problem, sorry but I can't fix it.
