### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by KeyboardChampion** [OrigamingWasTaken/appleblox#6]
It would be cool if you added more customizability to the ‘Draw Outlines’ option, because when you turn it on in some games, there are squares everywhere, which makes sense, but if I could make it only make boxes around player models, that would also be pretty cool.

**Comment by OrigamingWasTaken** [comment]
Sadly, this isn't possible as it is a Roblox fast flag, and is built-in. Also, I wouldn't add such feature (player outlines) as that could be used to gain an unfair advantage in games.
