### ISSUE TITLE
Functionality when joining private servers through links

### ISSUE THREAD

**Issue by kalberet** [OrigamingWasTaken/appleblox#8]
Hi, my AppleBlox settings don't seem to apply to instances created by private server links from browser. How do I get around this? Clicking "Write ClientAppSettings.json" before opening Roblox through the link doesn't have any changes and leaves me with a vanilla Roblox experience.

**Comment by AngrySausage** [comment]
1. Roblox sometimes doesn't open private server links. It isn't an Appleblox issue and all you need to do to fix it is **simply reload the page (DON'T CLICK THE PLAY BUTTON)**
2. There's no reason to click the "Write ClientAppSettings.json" button. If you have any issues loading Roblox normally with your flags send your Appleblox logs here. Also, are you sure clicking "Write ClientAppSettings.json" leaves you with a vanilla session?

**Comment by kalberet** [comment]
It's not that the private server links won't open, but rather there isn't a convenient way to join private servers through links with the AppleBlox configuration (other than writing it and copy pasting the ClientAppSettings file manually).

**Comment by AngrySausage** [comment]
Are you using nightly releases lol I forgot most people don’t use them.

Using the nightly release fixed slot of the issues you are probably having

here’s a link to it: [Nightly Releases](https://github.com/OrigamingWasTaken/appleblox/releases/latest)

**Comment by OrigamingWasTaken** [comment]
I'm currently working on fixing bugs and making the app stable so that's why I didn't make GitHub releases for the latest versions.

If you check the README, you can find a link to download the `0.7.1` version which implements launching from the web.

**Comment by kalberet** [comment]
> I'm currently working on fixing bugs and making the app stable so that's why I didn't make GitHub releases for the latest versions.
> 
> If you check the README, you can find a link to download the `0.7.1` version which implements launching from the web.

Thanks, this worked out well.
